name: printx
description: printx will allow to print object in colorize
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

